'use strict';

const $ = (id) => document.getElementById(id);
const text = (value) => String(value ?? '—');
const number = (value) => Number(value || 0);
const state = {
  runId: null, runStatus: '', view: 'actionable', page: 1, pendingOnly: true,
  selectedIds: new Set(), selectedJob: '', lastRefresh: null, lastFocus: null,
  controlPending: new Set(), refreshing: false, lastPlatformStates: new Map(),
  lastAnnouncement: '', lastControlMessage: '', lastRunSummary: '',
};
const PLATFORM_ORDER = ['linkedin', 'indeed', 'glassdoor'];
const HUMAN_READINESS = new Set(['challenged_cooldown', 'sign_in_required', 'user_action_required']);
const STATUS_LABEL = {
  WAITING_FOR_HUMAN: 'Waiting for you', SYSTEM_RETRYABLE: 'System retryable',
  SYSTEM_UNVERIFIED: 'System unverified', STALE: 'Worker connection stale',
  OFFLINE: 'Worker offline', INTERNAL_ERROR: 'Internal error', running: 'Running',
  rechecking: 'Rechecking', complete: 'Complete', stopped: 'Stopped', ready: 'Ready', idle: 'Waiting to run',
  'system-retryable': 'System retryable', 'system-unverified': 'System unverified',
  stale: 'Worker connection stale', offline: 'Worker offline', 'internal-error': 'Internal error',
};
const DISCOVERY_COLUMNS = [
  ['title_hint', 'Discovery'], ['platform', 'Platform'], ['company_hint', 'Company'],
  ['location_hint', 'Location'], ['card_metadata_status', 'Card'], ['content_state', 'Content'],
  ['detail_status', 'Detail'], ['observed_at', 'Observed'],
];
const displayColumns = [
  ['title', 'Role'], ['company', 'Company'], ['career_lane', 'Lane'], ['sources', 'Sources'],
  ['remote_gate', 'Remote'], ['content_state', 'Content'], ['recommendation', 'Decision'],
  ['door_score', 'Door'], ['application_status', 'Application'],
];

async function api(url, options = {}) {
  const response = await fetch(url, { cache: 'no-store', ...options });
  let value = {};
  try { value = await response.json(); } catch (_) { value = { error: `HTTP ${response.status}` }; }
  if (!response.ok || value.ok === false) throw new Error(value.error || value.message || `HTTP ${response.status}`);
  return value;
}
function setText(id, value) { const node = $(id); if (node) node.textContent = text(value); }
function setChildren(node, children) { node.replaceChildren(...children); }
function makeBadge(value, kind = 'neutral') { const span = document.createElement('span'); span.className = `state-badge ${kind}`; span.textContent = text(value); return span; }
function prettyDate(value) { if (!value) return 'Never'; const date = new Date(value); return Number.isNaN(date.valueOf()) ? text(value) : date.toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }
function humanWaiting(item) { const interaction = String(item.interaction_state || '').toUpperCase(); const readiness = String(item.readiness_state || '').toLowerCase(); const auth = String(item.auth_status || '').toLowerCase(); const worker = String(item.worker_status || '').toLowerCase(); return interaction === 'WAITING_FOR_HUMAN' || HUMAN_READINESS.has(readiness) || auth === 'not_authenticated' || ['challenged', 'paused', 'sign_in_required'].includes(worker); }
function statusKind(item) {
  const explicit = String(item.interaction_state || '').toUpperCase();
  if (explicit === 'WAITING_FOR_HUMAN' || humanWaiting(item)) return 'waiting-human';
  if (explicit === 'SYSTEM_RETRYABLE') return 'system-retryable'; if (explicit === 'SYSTEM_UNVERIFIED') return 'system-unverified';
  if (explicit === 'STALE') return 'stale'; if (explicit === 'OFFLINE') return 'offline'; if (explicit === 'INTERNAL_ERROR') return 'internal-error';
  if (explicit === 'RECHECKING') return 'rechecking'; if (explicit === 'COMPLETE') return 'complete'; if (explicit === 'STOPPED') return 'stopped';
  if (explicit === 'RUNNING') return 'running'; if (explicit === 'READY') return 'ready';
  const worker = String(item.worker_status || '').toLowerCase(); const readiness = String(item.readiness_state || '').toLowerCase();
  if (['stale', 'offline'].includes(worker)) return worker; if (['failed', 'error'].includes(worker)) return 'internal-error';
  if (readiness === 'retryable') return 'system-retryable'; if (['unverified', 'unknown'].includes(readiness)) return 'system-unverified';
  if (worker === 'rechecking') return 'rechecking'; if (worker === 'terminal' || (number(item.tasks_total) > 0 && number(item.tasks_completed) >= number(item.tasks_total))) return 'complete';
  if (worker === 'running' || number(item.running) > 0) return 'running'; if (worker === 'stopped') return 'stopped'; if (['verified', 'resumed'].includes(readiness)) return 'ready'; return 'idle';
}
function statusLabel(item) { const kind = statusKind(item); return STATUS_LABEL[kind === 'waiting-human' ? 'WAITING_FOR_HUMAN' : kind] || text(kind).replaceAll('-', ' '); }
function button(label, action, kind = 'subtle-button') { const node = document.createElement('button'); node.type = 'button'; node.className = kind; node.textContent = label; node.dataset.action = action; return node; }
function announce(message) { const value = String(message || ''); if (!value || value === state.lastAnnouncement) return; state.lastAnnouncement = value; if ($('liveRegion')) $('liveRegion').textContent = value; }
function setControlMessage(message) { const value = String(message || ''); if ($('controlMessage')) $('controlMessage').textContent = value; if (value && value !== state.lastControlMessage) announce(value); state.lastControlMessage = value; }

function renderIdentity(value) { setText('databasePath', value.resolved_database_path || 'Database unavailable'); setText('identityMeta', `Identity ${text(value.database_identity)} · JobBot ${text(value.jobbot_version)} · dashboard PID ${text(value.pid)}`); }
function renderSummary(value) {
  const labels = [['total', 'Ledger jobs', 'Authoritative records'], ['identity_captured', 'Cards persisted', 'Discovery identity'], ['descriptions_complete', 'Details complete', 'Substantive content'], ['enrichment_pending', 'Enrichment pending', 'Needs pane work'], ['qualified', 'Actionable', 'Qualification truth'], ['applications', 'Application events', 'Human history']];
  setChildren($('summary'), labels.map(([key, label, hint]) => { const article = document.createElement('article'); article.className = 'metric'; const name = document.createElement('span'); name.className = 'metric-label'; name.textContent = label; const val = document.createElement('strong'); val.textContent = number(value[key]); const caption = document.createElement('span'); caption.className = 'metric-caption'; caption.textContent = hint; article.append(name, val, caption); return article; }));
}
function renderAttention(value) {
  const items = value.attention || []; const region = $('attention');
  if (!items.length) { region.hidden = true; return; } region.hidden = false;
  const hasHuman = items.some((item) => item.state === 'WAITING_FOR_HUMAN'); $('attentionEyebrow').textContent = hasHuman ? 'ACTION OWNERSHIP' : 'SYSTEM ATTENTION'; $('attentionHeading').textContent = hasHuman ? 'Attention needed' : 'JobBot attention';
  setChildren($('attentionList'), items.map((item) => { const row = document.createElement('div'); row.className = 'attention-item'; const who = document.createElement('strong'); who.textContent = `${text(item.platform).toUpperCase()} · ${item.state === 'WAITING_FOR_HUMAN' ? 'Waiting for you' : text(item.owner || 'JobBot')}`; const reason = document.createElement('span'); reason.textContent = text(item.reason); const checkpoint = document.createElement('span'); checkpoint.textContent = item.checkpoint_preserved ? 'Checkpoint preserved' : 'Checkpoint status unavailable'; const next = document.createElement('span'); next.textContent = item.state === 'WAITING_FOR_HUMAN' ? 'Next: resolve the issue, then recheck once' : item.next_action === 'system_retry' ? 'Next: use the bounded system re-evaluation when available' : 'Next: review the durable diagnostic'; row.append(who, reason, checkpoint, next); return row; }));
}
function lifecycleText(item) { return `${item.owned_window ? 'Owned Chrome window preserved' : 'Chrome window not bound'} · ${item.search_tab_id ? 'reused search tab preserved' : 'search tab not bound'}`; }
function checkpointText(item) { const checkpoint = item.checkpoint || {}; if (!item.checkpoint_preserved && !checkpoint.preserved) return 'Checkpoint unavailable'; const page = number(checkpoint.page_number || item.current_page_number); const query = checkpoint.query || item.current_query; return `Preserved${page ? ` at page ${page}` : ''}${query ? ` · ${query}` : ''}`; }
function appendFact(facts, label, value) { const div = document.createElement('div'); const dt = document.createElement('dt'); dt.textContent = label; const dd = document.createElement('dd'); dd.textContent = text(value); div.append(dt, dd); facts.append(div); }

function renderPlatformCard(item) {
  const platform = text(item.platform).toLowerCase(); const kind = statusKind(item); const card = document.createElement('article'); card.className = `platform-card ${kind}`; card.setAttribute('aria-labelledby', `platform-${platform}-title`);
  const top = document.createElement('div'); top.className = 'platform-top'; const title = document.createElement('h3'); title.className = 'platform-title'; title.id = `platform-${platform}-title`; title.textContent = platform; const badge = document.createElement('span'); badge.className = `platform-status ${kind}`; badge.textContent = statusLabel(item); badge.setAttribute('aria-label', `Status: ${statusLabel(item)}`); top.append(title, badge); card.append(top);
  const sub = document.createElement('p'); sub.className = 'platform-subtitle'; const owner = text(item.state_owner || (kind === 'waiting-human' ? 'You' : 'JobBot')); sub.textContent = `${owner === 'You' ? 'You own' : `${owner} owns`} next step · ${lifecycleText(item)}`; card.append(sub);
  const facts = document.createElement('dl'); facts.className = 'platform-facts'; appendFact(facts, 'Current task', item.current_query || 'Waiting for next task'); appendFact(facts, 'Progress', `${number(item.tasks_completed)}/${number(item.tasks_total)} tasks · ${number(item.discoveries)} cards`); appendFact(facts, 'Details', `${number(item.details_complete)} complete · ${number(item.pending_details)} pending`); appendFact(facts, 'Last checked', prettyDate(item.last_checked_at || item.readiness_checked_at || item.worker_heartbeat_at)); appendFact(facts, 'Auth / readiness', `${text(item.auth_status)} / ${text(item.readiness_state)}`); appendFact(facts, 'Checkpoint', checkpointText(item)); card.append(facts);
  const reason = kind === 'waiting-human' ? (item.human_wait_reason || item.challenge_reason || item.readiness_reason || item.auth_reason || item.last_error) : kind === 'rechecking' ? '' : (item.readiness_reason || item.auth_reason || item.last_error || item.challenge_reason);
  if (reason) { const note = document.createElement('p'); note.className = `platform-reason ${kind}`; note.textContent = kind === 'waiting-human' ? `Reason: ${reason}` : `System report: ${reason}`; card.append(note); }
  if (kind === 'waiting-human') { const wait = document.createElement('section'); wait.className = 'human-wait-panel'; wait.setAttribute('aria-label', `${platform} human wait details`); const heading = document.createElement('h4'); heading.textContent = 'Waiting for you'; const explanation = document.createElement('p'); explanation.textContent = `Resolve the ${text(item.human_wait_reason || item.readiness_state || 'platform issue')} in the preserved Chrome window, then ask JobBot to check once.`; const proof = document.createElement('p'); proof.className = 'wait-proof'; proof.textContent = `${lifecycleText(item)} · ${checkpointText(item)}`; const reassurance = document.createElement('p'); reassurance.className = 'reassurance'; reassurance.textContent = 'JobBot will wait here. No automatic site retries.'; wait.append(heading, explanation, proof, reassurance); card.append(wait); }
  else if (['system-retryable', 'system-unverified', 'stale', 'offline', 'internal-error'].includes(kind)) { const ownership = document.createElement('p'); ownership.className = 'ownership-note'; ownership.textContent = kind === 'internal-error' ? 'JobBot owns this error. Review the durable report before retrying.' : 'JobBot owns the next step. This is not a human site clearance request.'; card.append(ownership); }
  const controlState = document.createElement('p'); controlState.className = 'platform-control-state'; if (state.controlPending.has(`${platform}:recheck`)) controlState.textContent = 'Recheck accepted · waiting for worker acknowledgement'; else if (item.control_status) controlState.textContent = `Control ${text(item.control_action).replaceAll('_', ' ')} · ${text(item.control_status).toLowerCase()}`; else controlState.textContent = ''; controlState.hidden = !controlState.textContent; card.append(controlState);
  const actions = document.createElement('div'); actions.className = 'platform-actions'; const focus = button('Focus Chrome window', 'focus_window'); focus.disabled = !item.window_id || state.controlPending.has(`${platform}:focus_window`); focus.setAttribute('aria-label', `Focus ${platform} Chrome window`); actions.append(focus); const stop = button(item.stop_after_current ? 'Stop pending' : 'Stop after current', 'stop_after_current'); stop.disabled = !!item.stop_after_current || ['complete', 'stopped'].includes(kind) || state.controlPending.has(`${platform}:stop_after_current`); stop.setAttribute('aria-label', `${item.stop_after_current ? 'Stop pending for' : 'Stop after current on'} ${platform}`); actions.append(stop);
  if (kind === 'waiting-human') { const recheck = button("I've resolved it — Recheck", 'recheck', 'primary-button'); recheck.disabled = state.controlPending.has(`${platform}:recheck`) || item.interaction_state === 'RECHECKING'; recheck.setAttribute('aria-label', `I've resolved the ${platform} issue — recheck ${platform} once`); actions.append(recheck); }
  else if (item.recovery_available && ['system-retryable', 'system-unverified', 'stopped'].includes(kind)) { const isStopped = kind === 'stopped'; const action = isStopped ? 'resume_platform' : 'retry_system_state'; const label = isStopped ? 'Resume platform' : 'Re-evaluate system state'; const recovery = button(label, action, isStopped ? 'subtle-button' : 'primary-button'); recovery.disabled = state.controlPending.has(`${platform}:${action}`); recovery.setAttribute('aria-label', `${label} on ${platform}`); actions.append(recovery); }
  actions.addEventListener('click', (event) => { const action = event.target?.dataset?.action; if (action) controlPlatform(platform, action, event.target); }); card.append(actions); return card;
}

function renderRun(value) {
  const run = value.run; const watch = value.watch || {}; const summary = value.run_state_summary || { label: run ? 'Run state available' : 'No run yet' }; state.runId = run?.browser_run_id || null; state.runStatus = text(run?.status || ''); setText('runIdentity', run ? `#${run.browser_run_id} · ${run.mode}` : 'No run'); setText('runStatus', run ? String(run.status).toUpperCase() : 'Waiting'); setText('lastProgress', prettyDate(run?.last_meaningful_progress_at || run?.last_progress_at)); setText('freshness', state.lastRefresh ? `Updated ${prettyDate(state.lastRefresh)}` : 'Loading'); setText('checkpointState', run?.last_error ? 'Review error / preserved' : 'Durable checkpoints'); setText('runSummary', summary.label || 'Run state available');
  const lines = []; if (watch.status) lines.push(`Watch ${watch.status} · phase ${watch.current_phase || 'idle'} · last cycle ${prettyDate(watch.last_cycle_at)}`); if (run) lines.push(`Run #${run.browser_run_id} · ${String(run.status).toUpperCase()} · ${number(run.jobs_recorded)} jobs recorded · last meaningful progress ${prettyDate(run.last_meaningful_progress_at || run.last_progress_at)}`); else lines.push('No browser run yet. Queue a bounded or production run from the launcher.'); $('runState').textContent = lines.join('\n');
  const items = [...(value.platforms || [])].sort((a, b) => PLATFORM_ORDER.indexOf(a.platform) - PLATFORM_ORDER.indexOf(b.platform)); const currentStates = new Map(items.map((item) => [item.platform, statusKind(item)])); if (state.lastPlatformStates.size) items.forEach((item) => { const previous = state.lastPlatformStates.get(item.platform); const current = currentStates.get(item.platform); if (previous && previous !== current) announce(`${text(item.platform)} is now ${statusLabel(item)}.`); }); state.lastPlatformStates = currentStates; if (summary.label && summary.label !== state.lastRunSummary && state.lastRunSummary) announce(summary.label); state.lastRunSummary = summary.label || ''; renderAttention(value); setChildren($('platformGrid'), items.length ? items.map(renderPlatformCard) : [Object.assign(document.createElement('p'), { className: 'inline-state', textContent: 'No platform worker state is available yet.' })]);
  if (value.global_control) setControlMessage(`Global control ${text(value.global_control.action).replaceAll('_', ' ')} · ${text(value.global_control.status).toLowerCase()}`); const runnable = value.runnable_resume || {}; $('stopRunButton').disabled = !run || ['completed', 'failed', 'stopped'].includes(String(run.status)); $('resumeRunButton').disabled = !run || number(runnable.runnable_task_count) === 0; $('resumeRunButton').setAttribute('aria-label', number(runnable.runnable_task_count) ? `Resume ${number(runnable.runnable_task_count)} runnable task(s) on ${(runnable.runnable_platforms || []).join(', ')}` : 'No runnable platform lanes'); $('emergencyRunButton').disabled = !run || ['completed', 'stopped', 'failed'].includes(String(run.status)); $('connectionBadge').textContent = 'SQLite state connected'; $('connectionBadge').className = 'status-pill ok';
}
function renderCoverage(value) { const rows = Object.entries(value.primary || {}); const max = Math.max(1, ...rows.map(([, item]) => number(item.total))); setChildren($('coverageGrid'), rows.map(([site, item]) => { const row = document.createElement('div'); row.className = 'coverage-row'; const name = document.createElement('strong'); name.textContent = site; const bar = document.createElement('div'); bar.className = 'coverage-bar'; bar.setAttribute('role', 'img'); bar.setAttribute('aria-label', `${site}: ${number(item.exhausted)} of ${number(item.total)} tasks exhausted`); const fill = document.createElement('div'); fill.className = 'coverage-fill'; fill.style.width = `${Math.round(number(item.exhausted) / max * 100)}%`; bar.append(fill); const count = document.createElement('span'); count.className = 'muted'; count.textContent = `${number(item.exhausted)}/${number(item.total)} exhausted`; row.append(name, bar, count); return row; })); const supplemental = Object.entries(value.supplemental || {}).map(([key, count]) => `${key} ${count}`).join(' · '); $('coverageNote').textContent = supplemental ? `Supplemental sightings: ${supplemental}` : 'Primary coverage is separate from canonical decision truth; deferred, incomplete, and challenged work remains visible.'; }
function renderGuide(value) { $('positioning').textContent = text(value.positioning); $('thesis').textContent = text(value.thesis); $('governingSentence').textContent = text(value.governing_sentence); setChildren($('portfolio'), (value.portfolio || []).sort((a, b) => number(a.execution_rank) - number(b.execution_rank)).map((lane) => { const chip = document.createElement('span'); chip.className = 'allocation-chip'; const percent = document.createElement('b'); percent.textContent = `${number(lane.allocation_percent)}%`; chip.append(percent, document.createTextNode(text(lane.label || lane.id))); return chip; })); setChildren($('scoreHelp'), Object.entries(value.score_weights || {}).map(([key, val]) => { const p = document.createElement('p'); const b = document.createElement('b'); b.textContent = `${key.replaceAll('_', ' ')}: `; p.append(b, document.createTextNode(text(val))); return p; })); setChildren($('recommendationHelp'), Object.entries(value.recommendations || {}).slice(0, 5).map(([key, val]) => { const p = document.createElement('p'); const b = document.createElement('b'); b.textContent = `${key}: `; p.append(b, document.createTextNode(text(val))); return p; })); }
function renderDiscoveries(value) { setText('pendingCount', `· ${number(value.pending)} pending`); $('discoveryState').textContent = value.discoveries?.length ? '' : 'No discoveries match this view. Fresh cards will appear here without blanking the workspace.'; setChildren($('discoveryHead'), DISCOVERY_COLUMNS.map(([, label]) => Object.assign(document.createElement('th'), { textContent: label }))); setChildren($('discoveryBody'), (value.discoveries || []).map((item) => { const tr = document.createElement('tr'); tr.tabIndex = 0; const open = () => item.source_url && window.open(item.source_url, '_blank', 'noopener'); tr.addEventListener('click', open); tr.addEventListener('keydown', (event) => { if (event.key === 'Enter') open(); }); DISCOVERY_COLUMNS.forEach(([key]) => { const td = document.createElement('td'); if (key === 'title_hint') { const strong = document.createElement('strong'); strong.className = 'discovery-title'; strong.textContent = text(item[key]) || 'Untitled discovery'; const sub = document.createElement('div'); sub.className = 'discovery-sub'; sub.textContent = `${text(item.source_job_id)} · ${text(item.query_text)}`; td.append(strong, sub); } else if (key === 'detail_status') { const valueText = text(item[key] || 'PENDING'); td.append(makeBadge(valueText, valueText === 'COMPLETE' && item.content_state === 'COMPLETE' ? 'complete' : valueText === 'FAILED' ? 'failed' : 'pending')); } else td.textContent = text(item[key]); tr.append(td); }); return tr; })); }
function queryParams() { const params = new URLSearchParams(new FormData($('filters'))); params.set('page', String(state.page)); params.set('page_size', '50'); if (state.view === 'actionable') params.set('view', 'actionable'); return params; }
function renderJobs(value) { setText('jobCount', `· ${number(value.total)}`); $('tableHint').textContent = state.view === 'actionable' ? 'Actionable view excludes out-of-scope and hard-gated records.' : 'All ledger records retain legitimate discoveries for audit.'; setChildren($('head'), [Object.assign(document.createElement('th'), { textContent: 'Select' }), ...displayColumns.map(([, label]) => Object.assign(document.createElement('th'), { textContent: label }))]); setChildren($('body'), (value.jobs || []).map((item) => { const tr = document.createElement('tr'); const checkbox = document.createElement('input'); checkbox.type = 'checkbox'; checkbox.dataset.id = item.job_id; checkbox.checked = state.selectedIds.has(item.job_id); checkbox.setAttribute('aria-label', `Select ${text(item.title)}`); checkbox.addEventListener('click', (event) => event.stopPropagation()); checkbox.addEventListener('change', () => checkbox.checked ? state.selectedIds.add(item.job_id) : state.selectedIds.delete(item.job_id)); const selectCell = document.createElement('td'); selectCell.append(checkbox); tr.append(selectCell); displayColumns.forEach(([key]) => { const td = document.createElement('td'); if (key === 'title') { td.className = 'job-title-cell'; const open = document.createElement('button'); open.type = 'button'; open.className = 'link-button'; open.textContent = text(item.title) || 'Untitled'; open.addEventListener('click', () => showJob(item.job_id, open)); const sub = document.createElement('span'); sub.textContent = text(item.job_id); td.append(open, sub); } else if (key === 'recommendation') td.append(makeBadge(item[key], String(item[key]).includes('APPLY') ? 'complete' : String(item[key]).includes('REVIEW') ? 'pending' : 'neutral')); else if (key === 'remote_gate') { td.className = 'evidence-cell'; const strong = document.createElement('strong'); strong.textContent = text(item[key]); const small = document.createElement('small'); small.textContent = item.remote_evidence_state === 'OBSERVED' ? 'Observed evidence' : 'Evidence incomplete'; td.append(strong, small); } else td.textContent = text(item[key]); tr.append(td); }); tr.addEventListener('dblclick', () => showJob(item.job_id, tr)); return tr; })); setText('page', `Page ${number(value.page)} · ${number(value.total)} records`); $('prev').disabled = state.page <= 1; $('next').disabled = state.page * number(value.page_size) >= number(value.total); $('tableState').textContent = value.jobs?.length ? 'Use the role button or double-click a row to inspect the decision brief.' : 'No records match the applied view. Try All ledger or clear filters.'; }
function renderList(target, items, labelKey = 'event_type') { setChildren(target, (items || []).map((item) => { const div = document.createElement('div'); div.className = 'timeline-item'; const strong = document.createElement('strong'); strong.textContent = text(item[labelKey] || item.status || item.source_site || 'Record'); div.append(strong, document.createTextNode(`${text(item.event_at || item.verified_at || item.first_seen || '')} · ${text(item.notes || item.message || item.source_url || '')}`)); return div; })); }
function renderJobDetail(value) { const job = value.job || {}; setText('detailTitle', job.title || 'Untitled role'); setText('detailCompany', job.company || 'Unknown company'); setText('detailMeta', `${text(job.location_raw || 'Location not observed')} · ${text(job.remote_gate)} · ${text(job.content_state)}`); setText('detailDescription', job.description || 'No substantive description is durable for this record.'); setText('detailWhy', job.recommendation || 'No recommendation'); setText('detailRemote', `${text(job.remote_gate)} · ${text(job.remote_evidence_state)}${job.remote_gate_reason ? `\n${job.remote_gate_reason}` : ''}`); setText('detailResume', job.resume_variant || 'No resume route recorded'); setText('detailRequirements', job.requirements_json || 'See full description and qualification evidence.'); setText('detailPreferred', job.preferred_json || 'No preferred evidence recorded.'); setChildren($('detailBadges'), [makeBadge(job.recommendation, job.recommendation === 'APPLY_NOW' ? 'complete' : 'pending'), makeBadge(job.content_state || 'MISSING', job.content_state === 'COMPLETE' ? 'complete' : 'pending')]); $('detailApply').href = job.canonical_url || '#'; setChildren($('detailScores'), [['Door', job.door_score], ['Fit', job.qualification_score], ['Career', job.career_score], ['Landing', job.landing_score], ['Relevance', job.relevance_score]].map(([label, score]) => { const div = document.createElement('div'); div.className = 'detail-score'; const span = document.createElement('span'); span.textContent = label; const strong = document.createElement('b'); strong.textContent = text(score); div.append(span, strong); return div; })); renderList($('detailSources'), value.occurrences || [], 'source_site'); renderList($('detailTimeline'), value.applications || [], 'status'); renderStatusActions(job.job_id, job.application_status); }
function renderStatusActions(jobId, current) { setChildren($('statusActions'), ['SHORTLIST', 'PREPARED', 'APPLIED', 'SCREEN', 'INTERVIEW', 'FINAL', 'OFFER', 'REJECTED', 'SKIP', 'CLOSED'].map((status) => { const b = document.createElement('button'); b.type = 'button'; b.textContent = status === current ? `✓ ${status}` : status; b.disabled = status === current; b.addEventListener('click', async () => { b.disabled = true; try { await api(`/api/jobs/${encodeURIComponent(jobId)}/application`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); $('detailNoteStatus').textContent = `Application history recorded: ${status}`; await refreshAll(); await showJob(jobId, b); } catch (error) { $('detailNoteStatus').textContent = error.message; } finally { b.disabled = false; } }); return b; })); }

async function showJob(jobId, focusOrigin = null) { state.selectedJob = jobId; state.lastFocus = focusOrigin || document.activeElement; $('jobDrawer').classList.add('open'); $('jobDrawer').setAttribute('aria-hidden', 'false'); $('detailError').hidden = true; $('detailLoading').hidden = false; $('detailContent').hidden = true; $('jobDrawer').setAttribute('aria-busy', 'true'); document.querySelector('main')?.setAttribute('inert', ''); document.querySelector('header')?.setAttribute('inert', ''); $('detailClose').focus(); try { const value = await api(`/api/jobs/${encodeURIComponent(jobId)}`); if (state.selectedJob === jobId) { renderJobDetail(value); $('detailContent').hidden = false; } } catch (error) { $('detailError').textContent = `Could not load job brief: ${error.message}. Close and try again.`; $('detailError').hidden = false; } finally { $('detailLoading').hidden = true; $('jobDrawer').setAttribute('aria-busy', 'false'); } }
function closeDrawer() { if (!$('jobDrawer').classList.contains('open')) return; $('jobDrawer').classList.remove('open'); $('jobDrawer').setAttribute('aria-hidden', 'true'); $('jobDrawer').removeAttribute('aria-busy'); document.querySelector('main')?.removeAttribute('inert'); document.querySelector('header')?.removeAttribute('inert'); state.selectedJob = ''; const origin = state.lastFocus; if (origin && document.contains(origin) && !origin.disabled) origin.focus(); else $('jobs').querySelector('button,input')?.focus(); }
function newControlRequestId() { if (window.crypto?.randomUUID) return `dashboard:${window.crypto.randomUUID()}`; const bytes = new Uint8Array(16); window.crypto?.getRandomValues?.(bytes); return `dashboard:${[...bytes].map((value) => value.toString(16).padStart(2, '0')).join('')}`; }
async function controlPlatform(platform, action, sourceButton) { const key = `${platform}:${action}`; if (state.controlPending.has(key) || !state.runId) return; const requestId = newControlRequestId(); state.controlPending.add(key); if (sourceButton) sourceButton.disabled = true; if (action === 'recheck') setControlMessage(`${platform} recheck accepted locally · waiting for durable acknowledgement…`); try { const value = await api('/api/platform/control', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ run_id: state.runId, platform, action, control_request_id:requestId }) }); setControlMessage(value.message || `Control ${action} recorded.`); await refreshRun(); } catch (error) { setControlMessage(`Control failed: ${error.message}`); } finally { state.controlPending.delete(key); if (sourceButton) sourceButton.disabled = false; await refreshRun(); } }
async function controlRun(action) { if (!state.runId) return; const requestId = newControlRequestId(); const buttonNode = action === 'stop_all' ? $('stopRunButton') : action === 'resume_ready_platforms' ? $('resumeRunButton') : $('emergencyRunButton'); setControlMessage(`Recording ${action.replaceAll('_', ' ')}…`); buttonNode.disabled = true; try { const value = await api('/api/run/control', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, run_id: state.runId, control_request_id:requestId }) }); setControlMessage(value.message || `Control ${action} recorded.`); await refreshRun(); } catch (error) { setControlMessage(`Control failed: ${error.message}`); } finally { buttonNode.disabled = false; await refreshRun(); } }
async function refreshRun() { try { renderRun(await api('/api/run')); } catch (error) { $('connectionBadge').textContent = 'State unavailable'; $('connectionBadge').className = 'status-pill bad'; $('runState').textContent = `Unable to read durable run state: ${error.message}\nExisting platform panels are preserved until the next successful refresh.`; } }
async function refreshAll() { if (state.refreshing) return; state.refreshing = true; state.lastRefresh = new Date(); setText('freshness', `Refreshing ${prettyDate(state.lastRefresh)}`); const results = await Promise.allSettled([api('/api/identity').then(renderIdentity), api('/api/summary').then(renderSummary), refreshRun(), api('/api/coverage').then(renderCoverage), api('/api/strategy').then(renderGuide), api(`/api/discoveries?limit=100${state.pendingOnly ? '&status=PENDING' : ''}`).then(renderDiscoveries), api(`/api/jobs?${queryParams()}`).then(renderJobs)]); if (results.some((result) => result.status === 'rejected')) { $('connectionBadge').textContent = 'Partial state'; $('connectionBadge').className = 'status-pill warn'; } state.refreshing = false; }
async function refreshJobs() { try { renderJobs(await api(`/api/jobs?${queryParams()}`)); } catch (error) { $('tableState').textContent = `Jobs unavailable: ${error.message}`; } }
function setView(view) { state.view = view; state.page = 1; $('actionableViewButton').classList.toggle('selected', view === 'actionable'); $('allViewButton').classList.toggle('selected', view !== 'actionable'); refreshJobs(); }
function quickFilter(kind) { $('filters').reset(); state.page = 1; state.view = 'actionable'; $('actionableViewButton').classList.add('selected'); $('allViewButton').classList.remove('selected'); document.querySelectorAll('.quick').forEach((b) => b.classList.remove('active')); if (kind === 'now') { $('filters').elements.recommendation.value = 'APPLY_NOW'; $('quickNowButton').classList.add('active'); } else if (kind === 'new') { $('filters').elements.change_status.value = 'NEW'; $('quickNewButton').classList.add('active'); } else if (kind === 'applied') { $('filters').elements.application_status.value = 'APPLIED'; $('quickAppliedButton').classList.add('active'); } else if (kind === 'qualified') $('quickQualifiedButton').classList.add('active'); refreshJobs(); }
document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && $('jobDrawer').classList.contains('open')) { event.preventDefault(); closeDrawer(); return; } if (event.key === 'Tab' && $('jobDrawer').classList.contains('open')) { const focusable = [...$('drawerCard').querySelectorAll('button,a[href],input,textarea,select,[tabindex]:not([tabindex="-1"])')].filter((node) => !node.disabled && !node.hidden); if (!focusable.length) return; const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } });
$('refreshButton').addEventListener('click', refreshAll); $('stopRunButton').addEventListener('click', () => controlRun('stop_all')); $('resumeRunButton').addEventListener('click', () => controlRun('resume_ready_platforms')); $('emergencyRunButton').addEventListener('click', () => { if (window.confirm('Persist an immediate stop? Committed data stays durable and unfinished work remains resumable.')) controlRun('emergency_stop'); }); $('pendingOnlyButton').addEventListener('click', () => { state.pendingOnly = !state.pendingOnly; $('pendingOnlyButton').textContent = state.pendingOnly ? 'Pending only' : 'Show all intake'; refreshAll(); }); $('actionableViewButton').addEventListener('click', () => setView('actionable')); $('allViewButton').addEventListener('click', () => setView('all')); $('quickQualifiedButton').addEventListener('click', () => quickFilter('qualified')); $('quickNowButton').addEventListener('click', () => quickFilter('now')); $('quickNewButton').addEventListener('click', () => quickFilter('new')); $('quickAppliedButton').addEventListener('click', () => quickFilter('applied')); $('quickResetButton').addEventListener('click', () => { $('filters').reset(); state.page = 1; state.view = 'all'; setView('all'); }); $('filters').addEventListener('submit', (event) => { event.preventDefault(); state.page = 1; refreshJobs(); }); $('prev').addEventListener('click', () => { if (state.page > 1) { state.page -= 1; refreshJobs(); } }); $('next').addEventListener('click', () => { state.page += 1; refreshJobs(); }); $('detailClose').addEventListener('click', closeDrawer); $('detailBackdrop').addEventListener('click', closeDrawer); $('guideToggleButton').addEventListener('click', () => { const open = $('guideContent').hidden; $('guideContent').hidden = !open; $('guideToggleButton').textContent = open ? 'Hide guide' : 'Show guide'; $('guideToggleButton').setAttribute('aria-expanded', String(open)); });
$('saveNoteButton').addEventListener('click', async () => { if (!state.selectedJob) return; const note = $('detailNote').value.trim(); if (!note) { $('detailNoteStatus').textContent = 'Enter a note first.'; return; } $('saveNoteButton').disabled = true; try { await api(`/api/jobs/${encodeURIComponent(state.selectedJob)}/note`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ note }) }); $('detailNote').value = ''; $('detailNoteStatus').textContent = 'Private note saved.'; await refreshAll(); await showJob(state.selectedJob, $('saveNoteButton')); } catch (error) { $('detailNoteStatus').textContent = error.message; } finally { $('saveNoteButton').disabled = false; } }); $('exportButton').addEventListener('click', async () => { const ids = [...state.selectedIds]; if (!ids.length) { $('message').textContent = 'Select at least one job first.'; return; } $('exportButton').disabled = true; try { const value = await api('/api/export-selected', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ job_ids: ids }) }); $('message').textContent = `Exported ${value.count} selected job(s) · ${value.path}`; } catch (error) { $('message').textContent = error.message; } finally { $('exportButton').disabled = false; } });
refreshAll(); window.setInterval(refreshAll, 10000);
