(() => {
  'use strict'; const C=globalThis.JobBotCommon; if(!C)return;
  function sid(url,el){try{const u=new URL(url,location.href);return C.clean(u.searchParams.get('jk')||u.searchParams.get('vjk')||el?.dataset?.jk||el?.getAttribute?.('data-jk')||'');}catch(_){return C.clean(el?.dataset?.jk||'');}}
  function canon(href){try{const u=new URL(href,location.href),id=u.searchParams.get('jk')||u.searchParams.get('vjk')||'';return id?`https://www.indeed.com/viewjob?jk=${encodeURIComponent(id)}`:u.href;}catch(_){return '';}}
  function collect(){const sels=['a[href*="/viewjob?jk="]','a[href*="/rc/clk?jk="]','h2.jobTitle a[href]','a[data-jk][href]','a[id^="job_"][href]'];const seen=new Map();for(const sel of sels)for(const a of document.querySelectorAll(sel)){const raw=C.absoluteUrl(a.getAttribute('href')||a.href||''),id=sid(raw,a),url=canon(raw);if(!id||!url)continue;const card=a.closest('[data-jk],.job_seen_beacon,.result,.cardOutline,li')||a.parentElement;const posted=C.clean(card?.querySelector?.('[data-testid="myJobsStateDate"],.date,[data-testid="job-age"]')?.innerText||'');seen.set(id,{source_job_id:id,url,title:C.clean(a.getAttribute('aria-label')||a.title||a.innerText||card?.querySelector?.('h2')?.innerText||''),company:C.clean(card?.querySelector?.('[data-testid="company-name"],.companyName,[data-testid="companyName"]')?.innerText||''),location:C.clean(card?.querySelector?.('[data-testid="text-location"],.companyLocation,[data-testid="job-location"]')?.innerText||''),posted_text:posted,posted_age_days:C.parseAgeDays(posted)});}return [...seen.values()];}
  function nextUrl(){for(const s of ['a[data-testid="pagination-page-next"][href]','a[aria-label="Next Page"][href]','a[aria-label="Next"][href]','nav a[aria-label*="Next"][href]']){const a=document.querySelector(s);if(a?.href)return C.absoluteUrl(a.href);}return '';}
  function inspectSearch(){const ch=C.challengeInfo(),body=C.clean(document.body?.innerText||'').toLowerCase();const login=/secure\.indeed\.com\/auth|\/account\/login/.test(location.href.toLowerCase())||(!!document.querySelector('a[href*="account/login"],a[href*="secure.indeed.com/auth"]')&&body.includes('sign in'));return{platform:'indeed',page_type:'search',challenged:ch.challenged,challenge_reason:ch.reason,login_required:login,page_url:location.href,result_links:collect(),next_url:nextUrl(),title:document.title};}
  function inspectAuth(){const ch=C.challengeInfo(),url=location.href.toLowerCase(),body=C.clean(document.body?.innerText||'').toLowerCase();const login=/secure\.indeed\.com\/auth|\/account\/login|\/account\/register/.test(url);const sign=!!document.querySelector('a[href*="account/login"],a[href*="secure.indeed.com/auth"]');const positive=body.includes('my jobs')||body.includes('saved jobs')||!!document.querySelector('[data-testid*="myjobs"],a[href*="/myjobs"]');const authenticated=!ch.challenged&&!login&&(positive||!sign);return{platform:'indeed',page_type:'auth',authenticated,challenged:ch.challenged,challenge_reason:ch.reason,page_url:location.href,reason:ch.challenged?ch.reason:(authenticated?'Indeed session authenticated':'Indeed sign-in required')};}
  function inspectJob(){const ch=C.challengeInfo(),x=C.parseJsonLdJob()||{};const title=x.title||C.firstText(['h1[data-testid="jobsearch-JobInfoHeader-title"]','h1.jobsearch-JobInfoHeader-title','h1']);const company=x.company||C.firstText(['[data-testid="inlineHeader-companyName"]','[data-company-name="true"]','.jobsearch-InlineCompanyRating-companyHeader a','.jobsearch-InlineCompanyRating-companyHeader']);const locationText=x.location||C.firstText(['[data-testid="inlineHeader-companyLocation"]','[data-testid="job-location"]','.jobsearch-JobInfoHeader-subtitle div']);const description=x.description||C.firstText(['#jobDescriptionText','[data-testid="jobsearch-JobComponent-description"]','.jobsearch-JobComponent-description','main'])||C.headingSectionText(['job description','about the job']);const salary=x.salary_text||C.firstText(['#salaryInfoAndJobType','[data-testid="attribute_snippet_testid"]','[data-testid="salary-snippet-container"]']);const posted=x.posted_at||C.firstText(['[data-testid="jobsearch-JobMetadataFooter"]','.jobsearch-JobMetadataFooter']);const id=sid(location.href,null),url=canon(location.href);return{platform:'indeed',page_type:'job',challenged:ch.challenged,challenge_reason:ch.reason,page_url:location.href,job:{source_job_id:id,canonical_url:url,apply_url:x.apply_url||url,title:C.clean(title),company:C.clean(company),location:C.clean(locationText),remote_status:/remote|work from home|wfh/i.test(`${locationText} ${description.slice(0,2500)}`)?'remote':'unknown',employment_type:C.clean(x.employment_type),salary_text:C.clean(salary),posted_at:C.clean(posted),posted_age_days:C.parseAgeDays(posted),valid_through:C.clean(x.valid_through),description:C.clip(description)}};}
  function inspect(){const p=location.pathname.toLowerCase();if(p.includes('/myjobs')||p.includes('/account/')||location.host.startsWith('secure.indeed.'))return inspectAuth();if(p.includes('/viewjob')||new URL(location.href).searchParams.has('jk')&&!p.includes('/jobs'))return inspectJob();return inspectSearch();}
  function advance(){const btn=document.querySelector('button[aria-label="Next Page"]:not([disabled]),button[aria-label="Next"]:not([disabled])');if(btn){btn.click();return{advanced:true,method:'click'};}return{advanced:false};}
  async function inspectJobEventually(){let last=inspectJob();for(let i=0;i<10&&(!last.job?.title||!last.job?.description);i++){await new Promise(r=>setTimeout(r,500));last=inspectJob();}return last;}
  chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='JOBBOT_INSPECT_AUTH'){send(inspectAuth());return true;}if(m?.type==='JOBBOT_INSPECT_SEARCH'){send(inspectSearch());return true;}if(m?.type==='JOBBOT_INSPECT_DETAIL'){inspectJobEventually().then(send);return true;}if(m?.type==='JOBBOT_INSPECT'){send(inspect());return true;}if(m?.type==='JOBBOT_SCROLL_AND_INSPECT'){C.scrollResults();setTimeout(()=>send(inspectSearch()),Math.max(500,Math.min(3000,Number(m.wait_ms||1200))));return true;}if(m?.type==='JOBBOT_ADVANCE_SEARCH'){const r=advance();setTimeout(()=>send({...r,page_url:location.href}),r.advanced?1200:0);return true;}return false;});
})();
