(() => {
  'use strict'; const C=globalThis.JobBotCommon; if(!C)return;
  function sid(url){try{const u=new URL(url,location.href);const m=u.pathname.match(/\/jobs\/view\/(\d+)/);return m?m[1]:C.clean(u.searchParams.get('currentJobId')||'');}catch(_){return '';}}
  function canon(href){try{const id=sid(href);return id?`https://www.linkedin.com/jobs/view/${id}/`:new URL(href,location.href).href;}catch(_){return '';}}
  function collect(){const sels=['a[href*="/jobs/view/"]','a.job-card-list__title','a.job-card-container__link'];const seen=new Map();for(const sel of sels)for(const a of document.querySelectorAll(sel)){const raw=C.absoluteUrl(a.getAttribute('href')||a.href||''),id=sid(raw),url=canon(raw);if(!id||!url)continue;const card=a.closest('li,.job-card-container,.jobs-search-results__list-item,.base-card')||a.parentElement;const posted=C.clean(card?.querySelector?.('time,.job-search-card__listdate,.job-card-container__listed-time,[class*="listed-time"]')?.innerText||card?.querySelector?.('time')?.getAttribute?.('datetime')||'');seen.set(id,{source_job_id:id,url,title:C.clean(a.innerText||a.getAttribute('aria-label')||''),company:C.clean(card?.querySelector?.('.job-card-container__primary-description,.artdeco-entity-lockup__subtitle,.base-search-card__subtitle')?.innerText||''),location:C.clean(card?.querySelector?.('.job-card-container__metadata-item,.job-search-card__location,.base-search-card__metadata')?.innerText||''),posted_text:posted,posted_age_days:C.parseAgeDays(posted)});}return [...seen.values()];}
  function nextUrl(){for(const s of ['a[aria-label="View next page"][href]','a[aria-label*="Next"][href]','button[aria-label="View next page"] + a[href]']){const a=document.querySelector(s);if(a?.href)return C.absoluteUrl(a.href);}try{const u=new URL(location.href),start=Number(u.searchParams.get('start')||0);if(collect().length>=5){u.searchParams.set('start',String(start+25));return u.href;}}catch(_){}return '';}
  function inspectAuth(){const ch=C.challengeInfo(),url=location.href.toLowerCase(),body=C.clean(document.body?.innerText||'').toLowerCase();const login=/\/login|\/checkpoint|\/authwall/.test(url);const sign=!!document.querySelector('a[href*="/login"],button[data-tracking-control-name*="signin"],a[data-tracking-control-name*="signin"]');const positive=body.includes('my jobs')||body.includes('saved jobs')||!!document.querySelector('a[href*="/my-items/saved-jobs"],a[href*="/jobs/collections"]');const authenticated=!ch.challenged&&!login&&(positive||!sign);return{platform:'linkedin',page_type:'auth',authenticated,challenged:ch.challenged,challenge_reason:ch.reason,page_url:location.href,reason:ch.challenged?ch.reason:(authenticated?'LinkedIn session authenticated':'LinkedIn sign-in required')};}
  function inspectSearch(){const ch=C.challengeInfo(),url=location.href.toLowerCase();const login=/\/login|\/checkpoint|\/authwall/.test(url);return{platform:'linkedin',page_type:'search',challenged:ch.challenged,challenge_reason:ch.reason,login_required:login,page_url:location.href,result_links:collect(),next_url:nextUrl(),title:document.title};}
  function inspectJob(){const ch=C.challengeInfo(),x=C.parseJsonLdJob()||{};const pageTitle=C.clean(document.title).replace(/\s*\|\s*LinkedIn\s*$/i,'').split('|')[0];const title=x.title||C.firstText(['h1.job-details-jobs-unified-top-card__job-title','h1[class*="job-title"]','h1','[data-test-job-title]'])||pageTitle;const company=x.company||C.firstText(['.job-details-jobs-unified-top-card__company-name a','.job-details-jobs-unified-top-card__company-name','.topcard__org-name-link','a[href*="/company/"]']);const locationText=x.location||C.firstText(['.job-details-jobs-unified-top-card__primary-description-container','.job-details-jobs-unified-top-card__tertiary-description-container','.topcard__flavor--bullet','a[aria-label*="Remote"]']);const description=x.description||C.firstText(['.jobs-description-content__text','.jobs-description__content','#job-details','.show-more-less-html__markup','[class*="jobs-description"]'])||C.headingSectionText(['about the job','job description']);const posted=x.posted_at||C.firstText(['.job-details-jobs-unified-top-card__tertiary-description-container time','time']);const id=sid(location.href),url=canon(location.href);return{platform:'linkedin',page_type:'job',challenged:ch.challenged,challenge_reason:ch.reason,page_url:location.href,job:{source_job_id:id,canonical_url:url,apply_url:x.apply_url||url,title:C.clean(title),company:C.clean(company),location:C.clean(locationText),remote_status:/remote|work from home|wfh/i.test(`${locationText} ${description.slice(0,2500)}`)?'remote':'unknown',employment_type:C.clean(x.employment_type),salary_text:C.clean(x.salary_text),posted_at:C.clean(posted),posted_age_days:C.parseAgeDays(posted),valid_through:C.clean(x.valid_through),description:C.clip(description)}};}
  function inspect(){const p=location.pathname.toLowerCase();if(p.includes('/my-items/')||p.includes('/login')||p.includes('/checkpoint')||p.includes('/authwall'))return inspectAuth();if(p.includes('/jobs/view/'))return inspectJob();return inspectSearch();}
  function advance(){const b=document.querySelector('button[aria-label="View next page"]:not([disabled]),button[aria-label*="Next"]:not([disabled])');if(b){b.click();return{advanced:true,method:'click'};}return{advanced:false};}
  async function inspectJobEventually(){let last=inspectJob();for(let i=0;i<12&&(!last.job?.title||!last.job?.description);i++){await new Promise(r=>setTimeout(r,600));last=inspectJob();}return last;}
  chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='JOBBOT_INSPECT_AUTH'){send(inspectAuth());return true;}if(m?.type==='JOBBOT_INSPECT_SEARCH'){send(inspectSearch());return true;}if(m?.type==='JOBBOT_INSPECT_DETAIL'){inspectJobEventually().then(send);return true;}if(m?.type==='JOBBOT_INSPECT'){send(inspect());return true;}if(m?.type==='JOBBOT_SCROLL_AND_INSPECT'){C.scrollResults();setTimeout(()=>send(inspectSearch()),Math.max(700,Math.min(3500,Number(m.wait_ms||1500))));return true;}if(m?.type==='JOBBOT_ADVANCE_SEARCH'){const r=advance();setTimeout(()=>send({...r,page_url:location.href}),r.advanced?1500:0);return true;}return false;});
})();
