(() => {
  'use strict'; const C=globalThis.JobBotCommon; if(!C)return;
  function sid(url){try{const u=new URL(url,location.href);const jl=u.searchParams.get('jl');if(jl)return jl;const m=u.pathname.match(/\/job-listing\/(.+?)-JV_/i);return m?m[1].slice(-80):u.pathname;}catch(_){return '';}}
  function canon(href){try{const u=new URL(href,location.href);u.hash='';return u.href;}catch(_){return '';}}
  function collect(){const sels=['a[href*="/job-listing/"]','a[data-test="job-link"][href]','a[class*="JobCard_jobTitle"][href]','a[class*="jobTitle"][href]'];const seen=new Map();for(const sel of sels)for(const a of document.querySelectorAll(sel)){const raw=C.absoluteUrl(a.getAttribute('href')||a.href||''),id=sid(raw),url=canon(raw);if(!id||!url)continue;const card=a.closest('li,[data-test="jobListing"],[class*="JobCard_jobCard"],[class*="jobCard"]')||a.parentElement;const txt=C.clean(card?.innerText||'');const ageMatch=txt.match(/(?:^|\s)(\d+\s*(?:d\+?|day(?:s)?|h|hr|hour(?:s)?|w|wk|week(?:s)?|mo|month(?:s)?))(?:\s|$)/i);const posted=C.clean(ageMatch?.[1]||card?.querySelector?.('[data-test="job-age"],[class*="listing-age"],[class*="job-age"]')?.innerText||'');seen.set(id,{source_job_id:id,url,title:C.clean(a.innerText||a.getAttribute('aria-label')||''),company:C.clean(card?.querySelector?.('[data-test="employer-name"],[class*="EmployerProfile_employerName"],[class*="employerName"]')?.innerText||''),location:C.clean(card?.querySelector?.('[data-test="emp-location"],[data-test="job-location"],[class*="location"]')?.innerText||''),posted_text:posted,posted_age_days:C.parseAgeDays(posted)});}return [...seen.values()];}
  function nextUrl(){for(const s of ['a[data-test="pagination-next"][href]','a[aria-label="Next"][href]','a[aria-label="Next Page"][href]','nav a[href][aria-label*="Next"]']){const a=document.querySelector(s);if(a?.href)return C.absoluteUrl(a.href);}return '';}
  function inspectAuth(){const ch=C.challengeInfo(),url=location.href.toLowerCase(),body=C.clean(document.body?.innerText||'').toLowerCase();const login=/\/profile\/login|\/member\/login|signin|sign-in/.test(url);const sign=!!document.querySelector('button[data-test="sign-in-button"],a[href*="login"],a[href*="sign-in"]');const positive=body.includes('notifications')||body.includes('my jobs')||body.includes('saved jobs');const authenticated=!ch.challenged&&!login&&(positive||!sign);return{platform:'glassdoor',page_type:'auth',authenticated,challenged:ch.challenged,challenge_reason:ch.reason,page_url:location.href,reason:ch.challenged?ch.reason:(authenticated?'Glassdoor session authenticated':'Glassdoor sign-in required')};}
  function inspectSearch(){const ch=C.challengeInfo();return{platform:'glassdoor',page_type:'search',challenged:ch.challenged,challenge_reason:ch.reason,login_required:false,page_url:location.href,result_links:collect(),next_url:nextUrl(),title:document.title};}
  function inspectJob(){const ch=C.challengeInfo(),x=C.parseJsonLdJob()||{};const title=x.title||C.firstText(['h1[data-test="job-title"]','h1[class*="heading"]','h1']);const company=x.company||C.firstText(['[data-test="employer-name"]','[class*="EmployerProfile_employerName"]','[class*="employerName"]']);const locationText=x.location||C.firstText(['[data-test="location"]','[data-test="job-location"]','[class*="location"]']);const description=x.description||C.firstText(['[data-test="jobDescriptionContent"]','[class*="JobDetails_jobDescription"]','[class*="jobDescription"]','main'])||C.headingSectionText(['job description','about the job']);const salary=x.salary_text||C.firstText(['[data-test="detailSalary"]','[class*="salary"]']);const posted=C.clean(x.posted_at||C.firstText(['[data-test="job-age"]','[class*="listing-age"]','time']));const id=sid(location.href),url=canon(location.href);return{platform:'glassdoor',page_type:'job',challenged:ch.challenged,challenge_reason:ch.reason,page_url:location.href,job:{source_job_id:id,canonical_url:url,apply_url:x.apply_url||url,title:C.clean(title),company:C.clean(company),location:C.clean(locationText),remote_status:/remote|work from home|wfh/i.test(`${locationText} ${description.slice(0,2500)}`)?'remote':'unknown',employment_type:C.clean(x.employment_type),salary_text:C.clean(salary),posted_at:posted,posted_age_days:C.parseAgeDays(posted),valid_through:C.clean(x.valid_through),description:C.clip(description)}};}
  function inspect(){const p=location.pathname.toLowerCase();if(p.includes('/member/')||p.includes('/profile/login'))return inspectAuth();if(p.includes('/job-listing/'))return inspectJob();return inspectSearch();}
  function advance(){const btn=[...document.querySelectorAll('button')].find(b=>!/disabled/i.test(String(b.disabled))&&/show more|next/i.test(C.clean(b.getAttribute('aria-label')||b.innerText||'')));if(btn&&!btn.disabled){btn.click();return{advanced:true,method:'click'};}return{advanced:false};}
  async function inspectJobEventually(){let last=inspectJob();for(let i=0;i<12&&(!last.job?.title||!last.job?.description);i++){await new Promise(r=>setTimeout(r,600));last=inspectJob();}return last;}
  chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='JOBBOT_INSPECT_AUTH'){send(inspectAuth());return true;}if(m?.type==='JOBBOT_INSPECT_SEARCH'){send(inspectSearch());return true;}if(m?.type==='JOBBOT_INSPECT_DETAIL'){inspectJobEventually().then(send);return true;}if(m?.type==='JOBBOT_INSPECT'){send(inspect());return true;}if(m?.type==='JOBBOT_SCROLL_AND_INSPECT'){C.scrollResults();setTimeout(()=>send(inspectSearch()),Math.max(700,Math.min(3500,Number(m.wait_ms||1500))));return true;}if(m?.type==='JOBBOT_ADVANCE_SEARCH'){const r=advance();setTimeout(()=>send({...r,page_url:location.href}),r.advanced?1600:0);return true;}return false;});
})();
